@startuml transmitter_state

[*] --> ESPERA_MENSAGEM
ESPERA_MENSAGEM --> ENVIA_STX : Mensagem recebida
ENVIA_STX --> ENVIA_QUANTIDADE
ENVIA_QUANTIDADE --> ENVIA_DADOS
ENVIA_DADOS --> ENVIA_DADOS
ENVIA_DADOS --> ENVIA_CHECKSUM
ENVIA_CHECKSUM --> ENVIA_ETX
ENVIA_ETX --> MENSAGEM_ENVIADA
MENSAGEM_ENVIADA --> ESPERA_MENSAGEM
@enduml